---
abstract: 'efficiently retrieve and search trees with DBIx::Class'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-MaterializedPath
requires:
  Class::C3::Componentised: 1.001000
  DBIx::Class: 0.08196
  DBIx::Class::Helpers: 2.007004
  SQL::Translator: 0.11011
  Sub::Current: 0.02
  Test::Deep: 0.110
  Test::More: 0.98
resources:
  repository: git://github.com/frioux/DBIx-Class-MaterializedPath.git
version: 0.002000
